name: SimpleBuild
on: push
jobs:
  build:
    name: Test compiling 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2
      with: 
        required-libraries: DFRobotDFPlayerMini,Bounce2
